name: Deploy Quasar SPA

on:
  push:
    branches:
      - swoole

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies & build
      run: |
        npm install
        npm run build

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY_UDUMBARA }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -p 2221 192.168.150.112 >> ~/.ssh/known_hosts

    - name: Upload to server via rsync
      run: |
        rsync -avz -e "ssh -p 2221" dist/spa/ root@192.168.150.112:/www/wwwroot/frontend.192.168.150.111/dist/
