name: Deploy Simrs SPA

on:
  push:
    branches:
      - swoole

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install & Build
      run: |
        npm install
        npm run build
        zip -r spa-build.zip dist/spa

    - name: Upload ZIP ke GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        files: spa-build.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Trigger webhook di server
      run: |
        curl -X POST "http://panelb.xenter.my.id/hook?access_key=Jlajy2eyH3BysC6DCSCkgGk0MXrOBMzaJETh5hPheivYoo6P"
